name: Create NuGet package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  create-package:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Build with dotnet
      run: dotnet build ImgwApi --configuration Release
    - name: Pack with dotnet
      run: dotnet pack ImgwApi --configuration Release -o Packed --no-build -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --version-suffix $(echo ${GITHUB_SHA} | cut -c1-8)
    - name: Upload package
      uses: actions/upload-artifact@v3
      with:
        name: package
        path: Packed
